/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.xxy.stock.web.action;

import javax.servlet.http.*;

import org.apache.struts.action.*;

/**
 * MyEclipse Struts
 * Creation date: 03-24-2008
 *
 * XDoclet definition:
 * @struts.action parameter="action" validate="true"
 */
public class LoginAction extends BaseAction {

    /**
     * Method execute
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return ActionForward
     */
    public ActionForward doExecute(ActionMapping mapping, ActionForm form,
                                   HttpServletRequest request,
                                   HttpServletResponse response) {


        // TODO Auto-generated method stub
        ActionMessages messages = new ActionMessages();
        
        String action = request.getParameter(ACTION);

        if (action == null || "".equalsIgnoreCase(action)) {
            return mapping.findForward(FWD_FAILURE);
        }
        else if (ACTION_FALSE.equalsIgnoreCase(action)) {
            return mapping.findForward(FWD_FAILURE);
        }
        else if (ACTION_LOGIN.equalsIgnoreCase(action)) {
            return doLogin(mapping, form, request, response);
        }
        else {
            messages.add(ActionMessages.GLOBAL_MESSAGE,
                         new ActionMessage("error.no.action"));
            saveMessages(request, messages);
            return mapping.findForward(FWD_FAILURE);
        }

    }

    @SuppressWarnings("deprecation")
	public ActionForward doLogin(ActionMapping mapping, ActionForm form,
                                 HttpServletRequest request,
                                 HttpServletResponse response) {

        ActionErrors errors = validateLogin(request);
        if (!errors.isEmpty()) {
            saveErrors(request, errors);
            return mapping.findForward(ACTION_FAILURE);
        }
        
        String name = request.getParameter("name");
        if("show-you".equals(name)){
        	request.getSession().setAttribute("king", Boolean.TRUE);
        }else{
        	request.getSession().setAttribute("king", Boolean.FALSE);
        }
        request.getSession().setAttribute(MY_ACCOUNT_ID, name);

        return mapping.findForward("success");

    }

    public ActionErrors validateLogin(HttpServletRequest httpServletRequest) {

        ActionErrors errors = new ActionErrors();

        String name = httpServletRequest.getParameter("name");
        String password = httpServletRequest.getParameter("password");
        if (name == null || name.trim().equals("")) {
            errors.add("error", new ActionMessage("madantory"));
        }
        if (password == null || password.trim().equals("")) {
            errors.add("error", new ActionMessage("madantory"));
        }
        if(!(("show-you".equals(name) && "show-you".equals(password)) 
        		|| ("admin".equals(name) && "admin".equals(password)))){
        	errors.add("error", new ActionMessage("invalid"));
        }

        return errors;

    }

}
