/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.xxy.stock.web.action;

import java.util.*;
import javax.servlet.http.*;

import org.apache.struts.action.*;

/**
 * MyEclipse Struts
 * Creation date: 03-24-2008
 *
 * XDoclet definition:
 * @struts.action parameter="action" validate="true"
 */
public class LogoutAction extends BaseAction {

    /**
     * Method execute
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return ActionForward
     */
    public ActionForward doExecute(ActionMapping mapping, ActionForm form,
                                   HttpServletRequest request,
                                   HttpServletResponse response) {

        // TODO Auto-generated method stub
        ActionMessages messages = new ActionMessages();

        String action = request.getParameter(ACTION);

        if (action == null || "".equalsIgnoreCase(action)) {
            return doLogout(mapping, form, request, response);
        }
        else if (ACTION_FALSE.equalsIgnoreCase(action)) {
            return doLogout(mapping, form, request, response);
        }
        else if (ACTION_LOGIN.equalsIgnoreCase(action)) {
            return doLogout(mapping, form, request, response);
        }
        else {
            messages.add(ActionMessages.GLOBAL_MESSAGE,
                         new ActionMessage("error.no.action"));
            saveMessages(request, messages);
            return mapping.findForward(FWD_FAILURE);
        }

    }

    public ActionForward doLogout(ActionMapping mapping, ActionForm form,
                                 HttpServletRequest request,
                                 HttpServletResponse response) {

        removeSesion(request.getSession());

        return mapping.findForward("success");

    }

    @SuppressWarnings("rawtypes")
	private void removeSesion(HttpSession session) {
        Enumeration enu = session.getAttributeNames();
        while(enu.hasMoreElements()){
            session.removeAttribute(String.valueOf(enu.nextElement()));
        }
    }


}
